#服务器端口
server:
  port: 36105

#数据源配置
spring:
  datasource:
    url: ${platform.datasource.prod.url}
    username: ${platform.datasource.prod.username}
    password: ${platform.datasource.prod.password}
