#服务器端口
server:
  port: 6100

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${platform.datasource.test.url}
    username: ${platform.datasource.test.username}
    password: ${platform.datasource.test.password}
