#服务器端口
server:
  port: 16100

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${platform.datasource.dev.url}
    username: ${platform.datasource.dev.username}
    password: ${platform.datasource.dev.password}
  zipkin:
    base-url: http://192.168.1.50:30002
    discovery-client-enabled: false # 不要让nacos把zipkin注册进去（可以不写）
  sleuth:
    sampler:
      probability: 1.0