#服务器端口
server:
  port: 37105

#数据源配置
spring:
  datasource:
    url: ${platform.datasource.test.url}
    username: ${platform.datasource.test.username}
    password: ${platform.datasource.test.password}
